### ISSUE TITLE
Clarification on distance calculation

### ISSUE THREAD

**Issue by sahilrider** [Subikshaa/Social-Distance-Detection-using-OpenCV#1]
`                distance = (165 * F)/height`

Is 165 height of the person?

**Comment by Merwanski** [comment]
Hey @sahilrider According to the description given yes the 165 correspond to the average height of humans in cm

**Comment by RuikunLi** [comment]
Hi, I have a question regarding the ocal length.
`F = 615` is the focal length of your camera, so in the project when I want to measure the depth distance of my camera, I have to first calculate the focal distance of the camera I used, right?
