### ISSUE TITLE
TypeError:only size-1 arrays can be converted to Python scala

### ISSUE THREAD

**Issue by Nagaraj4896** [Subikshaa/Social-Distance-Detection-using-OpenCV#2]
cv2.rectangle(frame, (startX, startY), (endX, endY), COLOR, 2)
TypeError: only size-1 arrays can be converted to Python scalars
this error came while giving video

**Comment by ashhadulislam** [comment]
replace 

```
if i in close_objects:
            COLOR = np.array([0,0,255])
        else:
            COLOR = np.array([0,255,0])


```

with

```
if i in close_objects:
            COLOR = (0,0,255)
        else:
            COLOR = (0,255,0)

```
lines 121-124
social_distance_detection.py

**Comment by skykrishnadon** [comment]
Traceback (most recent call last):
  File "social_distance_detection.py", line 127, in <module>
    cv2.rectangle(frame, (startX, startY), (endX, endY), COLOR, 2)
TypeError: only size-1 arrays can be converted to Python scalars
Above code doesnt worked

**Comment by tuanhm11299** [comment]
Hi, 
I replaced but error at line 126:
File "social_distance_detection.py", line 126, in <module>
    COLOR = np.array(0,255,0)
TypeError: array() takes from 1 to 2 positional arguments but 3 were given
